service:
  name: quiz-api

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function #allows to declare iamRoles per lambda 

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'} #use "dev" by default if there is not a stage defined
  region: sa-east-1 #deploy to this region and not to default

 
resources:
  Resources:
    QuestionsTable:                    #dynamodb questions table
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuestionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: questionId
            AttributeType: S
        KeySchema:
          - AttributeName: questionId
            KeyType: HASH


functions:
  getQuestions:
    handler: src/handlers/getQuestions.handler  #when a GET http request is recived at /questions, this lambda is triggered
    events:
      - http:
          method: GET
          path: /questions

  createQuestion:
    handler: src/handlers/createQuestion.handler
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/QuestionsTable
    events:
      - http:
          method: POST
          path: /admin/createquestion


#use to define custom variables
#custom:
